input {
  tcp {
    port => 5044
    codec => json_lines
  }
}

filter {
  if [service] == "rag-from-scratch" {
    mutate {
      add_field => { "[@metadata][index]" => "rag-logs" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "rag-logs-%{+YYYY.MM.dd}"
  }
}
